# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
