# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrapp', '0003_auto_20170726_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='UserManager',
        ),
    ]
