# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lrapp', '0004_auto_20170726_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Birthday',
        ),
    ]
